#
# https://gohugo.io/getting-started/configuration/#all-configuration-settings
#

baseURL = "https://www.rugan.me/" # Controls base URL
languageCode = "en-us" # Controls site language
title = "::: rugan.me :::" # Homepage title and page title suffix
theme = "after-dark" # Set default theme
paginate = 5 # Number of posts to show before paginating
enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "UA-1234567" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

# Highlight code fenced blocks, but only with language, e.g., ```.go
# fenced code blocks without language (e.g, ```) will not be highlighted
pygmentsCodeFences = true
pygmentsOptions = "linenos=true" # add line numbers to highlighted blocks

[[menu.main]]
	name = "Home"
	weight = 1
	identifier = "home"
	url = "/"
[[menu.main]]
	name = "Posts"
	weight = 2
	identifier = "posts"
	url = "/posts"
[[menu.main]]
	name = "About"
	weight = 3
	identifier = "about"
	url = "/about/"

[[params]]
	description = "" # Suggested, controls default description meta
	author = "" # Optional, controls author name display on posts
	hide_author = false # Optional, set true to hide author name on posts
	show_menu = false # Optional, set true to enable section menu
	powered_by = false # Optional, set false to disable credits
	images = [
		"https://source.unsplash.com/category/technology/1600x900"
	] # Suggested, controls default Open Graph images
	theme_variant = "hack dark-grey" # Optional, for use to overriding default theme